// export const FETCH_PRODUCTS_BEGIN   = 'FETCH_PRODUCTS_BEGIN';
// export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
// export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
// // export const EDIT_PRODUCT_QUANTITY = 'EDIT_PRODUCT_QUANTITY';
// export const ADD_CART_PRODUCT = 'ADD_CART_PRODUCT';
