export const ALLERGENS_UPDATE_REQUEST = "ALLERGENS_UPDATE_REQUEST";
export const ALLERGENS_UPDATE_SUCCESS = "ALLERGENS_UPDATE_SUCCESS";
export const ALLERGENS_UPDATE_FAIL = "ALLERGENS_UPDATE_FAIL";


export const ALLERGENS_CREATE_REQUEST = "ALLERGENS_CREATE_REQUEST";
export const ALLERGENS_CREATE_SUCCESS = "ALLERGENS_CREATE_SUCCESS";
export const ALLERGENS_CREATE_FAIL = "ALLERGENS_CREATE_FAIL";