export const ALLERGENS_TAB = [
  { name: "Milk", selected: false, value: "en:milk" },
  { name: "Gluten", selected: false, value: "en:gluten" },
  { name: "Eggs", selected: false, value: "en:eggs" },
  { name: "Soybeans", selected: false, value: "en:soybeans" },
  { name: "Nuts", selected: false, value: "en:nuts" },
  { name: "Fish", selected: false, value: "en:fish" },
  { name: "Mustard", selected: false, value: "en:mustard" },
  { name: "Celery", selected: false, value: "en:celery" },
  { name: "Sesame seeds", selected: false, value: "en:sesame-seeds" },
  { name: "Peanuts", selected: false, value: "en:peanuts" },
  { name: "Crustaceans", selected: false, value: "en:crustaceans" },
  { name: "Molluscs", selected: false, value: "en:molluscs" },
  { name: "Oats", selected: false, value: "fr:avoine" },
  { name: "Lupin", selected: false, value: "en:lupin" },
];
